# Generated by Django 2.2.5 on 2019-09-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='uname', max_length=50),
            preserve_default=False,
        ),
    ]
